### ISSUE TITLE
Little Problem

### ISSUE THREAD

**Issue by FAVOLEDIGITALI** [taniot/gravityforms-to-mailup#4]
Ciao, gran bel plugin ho riscontrato solo un bug.
Quando registro un utente già presente in una lista di mailup e non specifico il numero di cellulare (neanche presente nel modulo per capirsi) lui lo sovrascrive anche se è vuoto.
Hai qualche idea di come risolverla?

**Comment by taniot** [comment]
Ciao, grazie.
Purtroppo all'epoca dello sviluppo la libreria di MailUp non consentiva grandi controlli sui campi.
Ti faccio sapere se è cambiato qualcosa in merito :)

**Comment by taniot** [comment]
Ciao FAVOLEDIGITALI,
grazie per il complimento.

Per quanto riguarda i campi che vengono sovrascritti, il plugin di default sovrascrive i dati già presenti. Puoi modificare il comportamento del plugin grazie a questo filtro, che puoi inserire nel tuo file functions.php.

**//non sovrascrivere i campi degli utenti già registrati**
add_filter('gform_mailup_override_empty_fields', '__return_false' );

Fammi sapere.
A presto
