### ISSUE TITLE
Fatal error when plugin is activated

### ISSUE THREAD

**Issue by adrianogiannacco** [taniot/gravityforms-to-mailup#5]
Ciao,
io e i miei colleghi ti facciamo i complimenti per il plugin.
Oggi però al momento dell'attivazione del plugin ho ricevuto questo avviso:

_Il plugin non può essere attivato perché genera un errore fatale._

**Fatal error:** Cannot redeclare gf_mailup() (previously declared in /home/sitodiesempio/public_html/wp-content/plugins/gravityforms-to-mailup/mailup.php:39) in /home/sitodiesempio/public_html/wp-content/plugins/gravityforms-to-mailup-master/mailup.php on line 40

Ti ringrazio in anticipo e ti auguro buon lavoro.

Adriano

**Comment by taniot** [comment]
CIao Adriano,
grazie :)

Per quanto riguarda l'errore, credo abbiate, nella cartellina

/wp-content/plugins/

2 versioni del plugin in 2 cartelle diverse
gravityforms-to-mailup
gravityforms-to-mailup-master

Ti consiglio di rimuoverli entrambi via FTP e ricaricare il plugin, così non perderai le configurazioni.
Fammi sapere

**Comment by adrianogiannacco** [comment]
Grazie mille,
è esattamente così! Il motivo al momento mi sfugge, ma tant'è :)
Ora il funzionamento è corretto come al solito.
Grazie ancora, un saluto

Adriano
